<?php

namespace Payment\Common\Qpay\Data;

use Payment\Common\BaseData;
use Payment\Common\PayException;
use Payment\Utils\ArrayUtil;

/**
 * Class QpayBaseData
 * @package Payment\Common\Qpay\Data
 *
 * @author: Benny <benny_a8@live.com>
 * @createTime: 2019-01-08 18:45
 * @description: qpay 基础数据
 */
abstract class QpayBaseData extends BaseData
{

    protected function checkDataParam()
    {

    }


    protected function makeSign($signStr)
    {
        return $signStr;
    }

    protected function buildData()
    {
        $signData = [
            // 公共参数
            'version' => $this->version,
            'charset' => $this->charset,
            'signType' => $this->signType,
            'reqData' => $this->getReqData(),
        ];

        // 移除数组中的空值
        $this->retData = ArrayUtil::paraFilter($signData);
    }

    public function setSign()
    {
        parent::setSign(); // TODO: Change the autogenerated stub
    }

    public function getData()
    {
        return parent::getData(); // TODO: Change the autogenerated stub
    }


}
